services:
  app:
    build:
      context: .
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: sh -c "npm run dev"
volumes:
  node_modules: